package.json
src/datetime.ts
src/entries/summary.ts
src/plotly/datetime.ts
src/plotly/index.ts
tests/datetime.test.ts

Support datetime question type

work for the https://github.com/surveyjs/survey-analytics/issues/160

---

src/plotly/selectBase.ts
src/selectBase.ts
src/visualizerBase.ts

see https://surveyjs.answerdesk.io/internal/ticket/details/T8169

Implement `showOnlyPercentages` property

---

src/plotly/rating.ts

see https://github.com/surveyjs/service/issues/188

Analytics examples: Gauge Chart Customization issues

---

src/plotly/setup.ts

see https://github.com/surveyjs/survey-analytics/issues/213

Remove the whitespaces in stacked bar

---

src/plotly/setup.ts
tests/plotlyconfig.test.ts

see https://github.com/surveyjs/survey-analytics/issues/215

Long tick labels (coords) truncate problem

---

src/plotly/setup.ts
tests/plotlyconfig.test.ts

Matrix: HoverTexts (long tick labels) problem

---

src/selectBase.ts
tests/matrix.test.ts

see https://github.com/surveyjs/survey-analytics/issues/219

percentagePrecision option

---

src/visualizerBase.ts

Add a code example to `registerToolbarItems`

---

src/plotly/setup.ts
src/selectBase.ts
tests/selectBase.test.ts

Fixed #386 - Uncaught TypeError: Cannot read properties of undefined (reading 'marker')

---

docs/get-started-react.md

Get Started React - Fix an embedded demo link

---

src/visualizationManager.ts
tests/visualizationManager.test.ts

Implemented #427 - Implement an API to make a visualizer default

---

examples/summary.js
src/visualizationManager.ts
src/visualizationPanel.ts
src/visualizerBase.ts
tests/visualizationManager.test.ts

Implemented #433 - Introduce an option to hide charts of non-visualized questions

---

examples/tabulator-remote.html
examples/tabulator-remote.js
src/tables/table.ts
src/tables/tabulator.ts

Resolved #329 - Tabulator - Server-Side (Remote) Pagination

---

src/tables/tabulator.ts

Issue in survey tables in remote pagination in survey analytics version v2.0.0-rc-0 and pdf export

---

src/plotly/selectBase.ts
src/visualizationPanel.ts
src/visualizerBase.ts
tests/visualizationPanel.test.ts

A visualization panel flickers when the VisualizationPanel.updateData() function is called

---

src/tables/tabulator.ts
tests/tables/tabulator.test.ts

[BUG] The main search filter does not work at all.

---

src/plotly/setup.ts
tests/plotlyconfig.test.ts

Multi-Select Matrix - The Stacked Bar appears squeezed

---

src/selectBase.ts
tests/selectBase.test.ts

Cannot visualize a Specialized Question Type based on a Dropdown

---

.eslintrc.json
package.json

work for the https://github.com/surveyjs/service/issues/3361

PR: Analytics: Eslint Plugin from Github

---

src/selectBase.ts
tests/selectBase.test.ts

Filtering doesn't work for QuestionRatingModel in SelectBase visualizer
